services:
  postgres-db:
    image: postgres:15-alpine
    container_name: my_fastapi_app_postgres_db
    restart: always
    environment:
      POSTGRES_USER: my_fastapi_pg_user
      POSTGRES_PASSWORD: my_fastapi_pg_password
      POSTGRES_DB: my_fastapi_pg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  my_fastapi_app_redis:
    image: redis:7-alpine
    container_name: my_fastapi_app_redis
    ports:
      - "6379:6379"
    restart: always


  redis-insight:
    image: redis/redisinsight:latest
    container_name: my_fastapi_app_redis_insight
    ports:
      - "5504:5540"
    volumes:
      - redis_insight_data:/data
    depends_on:
      - my_fastapi_app_redis

  
  web:
    build: .
    container_name: my_fastapi_app_web
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres-db
      - DATABASE_PORT=5432
      # - DATABASE_USER=${DATABASE_USER}
      # - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      # - DATABASE_NAME=${DATABASE_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - postgres-db
      - my_fastapi_app_redis
    restart: always

volumes:
  postgres_data:
  redis_insight_data: