services:
  postgres-db:
    image: postgres:15-alpine
    container_name: my_firstapi_app_postgres_db
    restart: always
    environment:
      POSTGRES_USER: my_firstapi_pg_user
      POSTGRES_PASSWORD: my_firstapi_pg_password
      POSTGRES_DB: my_firstapi_pg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: